import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";

const libre = Libre_Franklin({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"]
});


export const metadata: Metadata = {
  title: "Net Mekkala App",
  description: "Generated by Mekkala",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libre.className}`}
      >
        {children}
      </body>
    </html>
  );
}
